# -*- coding: utf-8 -*-
"""Insurance_Fraud_Detection_Using_Decision_Tree.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1rKV6EQ5f3H2ZIn4lFHMpjeZPDFx67Q3Z
"""

import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

df=pd.read_csv('/content/insurance_claims.csv')
df

df.head()

df.tail()

df.shape

df.info()

df.describe()

df.isnull().sum()

df.replace("?", np.nan ,inplace=True)
df.head(15)

!pip install missingno

import missingno as msno
msno.bar(df)

df.isnull().sum()

from sklearn.impute import SimpleImputer
imp=SimpleImputer(strategy='most_frequent')
df[['collision_type']] = imp.fit_transform(df[['collision_type']])
df[['property_damage']] = imp.fit_transform(df[['property_damage']])
df[['police_report_available']] = imp.fit_transform(df[['police_report_available']])
df[['authorities_contacted']] = imp.fit_transform(df[['authorities_contacted']])
df

df.drop('_c39', axis=1, inplace=True)

num_cols = df.select_dtypes(include=np.number).columns
Q1 = df[num_cols].quantile(0.25)
Q3 = df[num_cols].quantile(0.75)
IQR = Q3 - Q1
lower_bound = Q1 - 1.5 * IQR
upper_bound = Q3 + 1.5 * IQR
df = df[((df[num_cols] < lower_bound) | (df[num_cols] > upper_bound)).any(axis=1)]
print(df.shape)

from scipy.stats.mstats import winsorize
numeric_cols=df.select_dtypes(include= np.number).columns
for col in numeric_cols:
  df[col]=winsorize(df[col], limits=[0,0.1])
print(df)

import seaborn as sns
sns.boxplot(df)

from sklearn.preprocessing import LabelEncoder
le = LabelEncoder()
cols = df.select_dtypes(include = 'object').columns
for col in cols:
    df[col] = le.fit_transform(df[col].astype(str))
print(df)

X=df.drop('fraud_reported',axis=1)
y=df['fraud_reported']

from sklearn.tree import DecisionTreeClassifier
from sklearn.model_selection import train_test_split
from sklearn.metrics import accuracy_score

X_train,X_test,y_train,y_test=train_test_split(X,y,random_state = 42,test_size=0.2)

model=DecisionTreeClassifier(criterion='entropy',max_depth=5,random_state = 42)
model.fit(X,y)

y_pred=model.predict(X_test)

print("accuracy score:", accuracy_score(y_pred,y_test))

print(df.shape)
print(y.value_counts())
print(X_train.shape)
print(X_test.shape)

df.shape

print("accuracy score:", accuracy_score(y_pred,y_test))

df = df.drop([
    "policy_number", "policy_bind_date", "insured_zip", "incident_location",
    "incident_city", "insured_sex", "insured_relationship", "policy_state",
    "incident_state", "property_claim", "age", "policy_deductable",
    "umbrella_limit", "insured_occupation", "insured_education_level",
    "capital-gains", "capital-loss", "auto_make", "auto_model",
    "authorities_contacted", "policy_annual_premium", "insured_hobbies", "_c39"
], axis=1, errors='ignore')

df.shape

X = df.drop('fraud_reported', axis=1)
y = df['fraud_reported']

X_train, X_test, y_train, y_test = train_test_split(X, y, random_state=42, test_size=0.2)

model = DecisionTreeClassifier(criterion='entropy', max_depth=5, random_state=42)
model.fit(X_train, y_train)

y_pred = model.predict(X_test)
print("Accuracy score:", accuracy_score(y_pred, y_test))

from sklearn.metrics import classification_report, confusion_matrix

print("Classification Report:")
print(classification_report(y_test, y_pred))

print("Confusion Matrix:")
print(confusion_matrix(y_test, y_pred))

from sklearn.tree import plot_tree

plt.figure(figsize=(25, 20))
plot_tree(model, feature_names=X.columns, class_names=['No Fraud', 'Fraud'], filled=True, rounded=True, fontsize=10)
plt.title('Decision Tree Structure')
plt.show()